services:
  - type: web
    name: mace-connect
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FIREBASE_CONFIG
        sync: false
      - key: GOOGLE_SHEETS_CREDENTIALS
        sync: false
      - key: SECRET_KEY
        generateValue: true
